# Python Basics

Introduces the core concepts of Python programming such as syntax, loops, functions, lists, and dictionaries.

In [2]:
x = 10
y = 5
print(x + y)

15


# Loops

Used to repeatedly execute a block of code based on a condition or sequence.

for loop

In [81]:
for i in range(3):
    print(i)

0
1
2


while loop

In [85]:
i = 0
while i < 3:
    print(i)
    i += 1

0
1
2


nested loop

In [87]:
for i in range(2):
    for j in range(2):
        print(i, j)

0 0
0 1
1 0
1 1


# Functions

Reusable blocks of code designed to perform a specific task.

Function with parameters

In [16]:
def add(a, b):
    return a + b

print(add(3, 4))

7


Function without parameters

In [72]:
def greet():
    print("Hello")

greet()

Hello


Function with default parameter

In [75]:
def power(x, y=2):
    return x ** y

print(power(3))

9


Lambda function

In [78]:
square = lambda x: x * x
print(square(5))

25


# Lists

Ordered and mutable collections used to store multiple items in a single variable.

In [23]:
nums = [1, 2, 3]

In [25]:
nums.append(4)        # add element
nums.insert(1, 10)    # insert at index
nums.remove(2)        # remove element
nums.pop()            # remove last
nums.extend([5, 6])   # add multiple
nums.sort()           # sort list
nums.reverse()        # reverse list
print(nums.count(3)) # count element
print(nums.index(3)) # find index
nums.clear()          # remove all
print(nums)

1
3
[]


# Dictionaries

Key-value pair data structures used for fast data lookup and organization.

In [28]:
# List ➝ Dictionary
keys = ['a', 'b', 'c']
values = [1, 2, 3]
d = dict(zip(keys, values))
print(d)

{'a': 1, 'b': 2, 'c': 3}


In [30]:
# Dictionary ➝ List
print(list(d.keys()))
print(list(d.values()))
print(list(d.items()))

['a', 'b', 'c']
[1, 2, 3]
[('a', 1), ('b', 2), ('c', 3)]


In [32]:
# Tuple inside dictionary
student = {
    "name": "Ali",
    "marks": (85, 90, 88)
}
print(student)

{'name': 'Ali', 'marks': (85, 90, 88)}


# NumPy

A Python library used for numerical computing and efficient array operations.

In [35]:
import numpy as np

# Arrays

NumPy’s core data structure used to store and process numerical data efficiently.

In [38]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


# Vectorized Operations

Operations performed on entire arrays at once without using explicit loops.

In [41]:
arr = np.array([1, 2, 3])
print(arr * 2)   # no loop needed
print(arr + 5)

[2 4 6]
[6 7 8]


# NumPy Advanced

# Matrix Multiplication

A mathematical operation that multiplies rows of one matrix with columns of another.

In [64]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = A @ B
print(result)

[[19 22]
 [43 50]]


# Broadcasting

A NumPy feature that allows operations between arrays of different shapes.

In [62]:
arr = np.array([1, 2, 3])
scalar = 5

print(arr + scalar)

[6 7 8]
